### DISCUSSION TITLE
2022-10-02

### DISCUSSION THREAD

**Discussion by vivipure** [vivipure/TIL#44] [Ideas]
看阮一峰的周刊发现一个文章挺有意思的，可以将通过css将源码暴露出来。

网址： https://secretgeek.github.io/html_wysiwyg/html.html

代码原理很简单，利用伪元素，在每个元素的前后添加对应的开闭标签
```css
html::before {content:'<html>'}
html::after {content:'</html>'}
head::before {content:'<head>'}
head::after {content:'</head>'}
title::before {content:'<title>'}
title::after {content:'</title>'}
body::before {content:'<body>'}
body::after {content:'</body>'}
h1::before {content:'<h1>'}
h1::after {content:'</h1>'}
h2::before {content:'<h2>'}
h2::after {content:'</h2>'}
p::before {content:'<p>'}
p::after {content:'</p>'}
pre::before {content:'<pre>'}
pre::after {content:'</pre>'}
code::before {content:'<code>'}
code::after {content:'</code>'}
a::before {content:'<a>'}
a::after {content:'</a>'}
aside::before {content:'<aside>'}
aside::after {content:'</aside>'}
blockquote::before {content:'<blockquote>'}
blockquote::after {content:'</blockquote>'}
em::before {content:'<em>'}
em::after {content:'</em>'}
strong::before {content:'<strong>'}
strong::after {content:'</strong>'}
```
当然每个元素都要设置对应的margin,保证能够展示完整
```html
*{ font-family:Monospace; margin:1.5em 0; padding:0; text-decoration:none}

```
同时也有对特殊元素进行一些处理
