### ISSUE TITLE
Transition 组件使用

### ISSUE THREAD

**Issue by vivipure** [vivipure/TIL#32]
# 介绍
Transition 组件是 Vue 的内置组件,用于组件内部的发生变化时提供切换的动效。
场景：
1. v-if/v-show
2. 动态组件
3. 组件根节点

Transition 组件在动画变化时，提供 className 的变化，也提供JS hook。

# class
![](https://v2.vuejs.org/images/transition.png)

- v-enter-active
   - v-enter
   - v-enter-to
- v-leave-active
   - v-leave
   - v-leave-to

`v`是 Transition 组件的name, 在使用CSS transition 时，我们可以定义 v-enter,v-leave-to 的状态，来配置动画
```css
.slide-fade-enter-active {
  transition: all .3s ease;
}
.slide-fade-leave-active {
  transition: all .8s cubic-bezier(1.0, 0.5, 0.8, 1.0);
}
.slide-fade-enter, .slide-fade-leave-to
/* .slide-fade-leave-active below version 2.1.8 */ {
  transform: translateX(10px);
  opacity: 0;
}
```
在使用 CSS animation 时，可以定义 v-enter-active, v-leave-active 的动画
```css

.bounce-enter-active
 {
  animation: bounce-in .5s;
}.
bounce-leave-active { 
 animation: bounce-in .5s reverse;
}
@keyframes bounce-in  {  
0% {    transform: scale(0);  }  
50% {    transform: scale(1.5);  }  
100% {    transform: scale(1);  }
}
```
Transtion 也提供自定义className 的属性

1. enter-class
2. enter-active-class
3. enter-to-class (2.1.8+)
4. leave-class
5. leave-active-class
6. leave-to-class (2.1.8+)

注意点：
1. Transition 组件通过监听 transitionend 或者 animationend 时间来执行结束hook.当两种动画同时执行时，需要手动指定type属性，告诉 Transition 组件使用哪种事件监听
2. 除了在 css 中定义动画事件，也可以使用 duration 属性定义动画的执行时间

# JavaScript
